### ISSUE TITLE
Multidomain example

### ISSUE THREAD

**Issue by Fayozjon** [ymigval/laravel-indexnow#1]
Hello. Can you show how to integrate on saas (multidomain)?

**Comment by ymigval** [comment]
You can host or create an implementation to use a specific text key file for each subdomain and instruct the package which key file to use.

Example:

```php
IndexNow::keyFile('https://nature.example.com/8bbf5df8bbaa457aab35bb3ccbb99aec.txt')
   ->submit('https://nature.example.com/cats');
```

Remember to update the package to use this feature.

**Comment by Fayozjon** [comment]
Thanks dude! Awesome!
